version: "3"
services:
  web:
    build: .
    image: web_image_latest
    container_name: web_container_latest
    env_file:
      - .env
      - flaskr/auth0/auth0.env
      - flaskr/db/db.env
    ports:
      -  ${PORT}:${PORT}
    volumes:
      - .:/app
  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}